### ISSUE TITLE
rrror "Could not locate data" when adding a lot of files to dat.archive

### ISSUE THREAD

**Issue by derhuerst** [datproject/dat-node#171]
This looks very similar to joehand/dat-next#122, but as suggested I'm cross-posting here, because I use `dat-node` directly.

[In `build-wikipedia-feed`, I'm directly calling `dat.archive.writeFile`](https://github.com/derhuerst/build-wikipedia-feed/blob/ad280775307c5fe5e4a525dae7576921c9a7fbd0/lib/write-to-hyperdrive.js#L17). It fails reproducibly after 128 pages with the following error:

```
Error: Could not locate data
    at /root/wiki-dumps/build-wikipedia-feed/node_modules/dat-storage/index.js:61:30
    at loop (/root/wiki-dumps/build-wikipedia-feed/node_modules/dat-storage/index.js:132:19)
    at /root/wiki-dumps/build-wikipedia-feed/node_modules/dat-storage/index.js:97:5
    at /root/wiki-dumps/build-wikipedia-feed/node_modules/hypercore/index.js:1107:5
    at onread (/root/wiki-dumps/build-wikipedia-feed/node_modules/random-access-file/index.js:130:14)
    at FSReqWrap.wrapper [as oncomplete] (fs.js:665:17)
```

**Comment by derhuerst** [comment]
turns out I already reported this once at https://github.com/mafintosh/hyperdrive/issues/154#issuecomment-320746714 . also, the link to project-related #165 might be useful.

**Comment by derhuerst** [comment]
To give you more details, this is the full log with `env 'DEBUG=*'`: [errlog.txt](https://github.com/datproject/dat-node/files/1345083/errlog.txt)
