### ISSUE TITLE
How to properly close dat so memory goes down

### ISSUE THREAD

**Issue by AcidLeroy** [datproject/dat-node#223]
I am reporting:

- [x] a bug or unexpected behavior
- [ ] general feedback
- [ ] feature request
- [ ] security issue 

# Bug Report

Please give us details about your installation to assist you. Run `dat -v` to see the version of Dat you are using.

* Operating system:OS X mojave
* Node Version: 10.9.0
* dat-node Version: 3.5.13

### Expected behavior

I expect this function to gracefully close when `dat.close()`is called. The reason I want to do this is because I found that memory continues to increase if I continually open dats and then can't close them. 

```js
// Load and close dats one at a time.
// ISSUE: Where would one put the close??
function loadOne(key) {
  return new Promise((resolve, reject) => {
    Dat('./test', {
      key: key,
      temp: true,
    }, (err, dat) => {
      if (err) reject(err)
      dat.joinNetwork((e) => {
        if (e) reject(e)
        dat.archive.readFile('/data.json', function(err, content) {
          if (err) reject(err)
          console.log('Donezies with ', key)
          if (!content) reject('NO CONTENT??')
          // *TRY* to close dat
          dat.close(() =>{
            console.log('Trying to close!')
            resolve(content.toString())
          })
        })
      })
    })
  })
}
```

### Actual behavior

I get an error: 
```
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: Feed is closed
    at Feed._onclose (/Users/cody/junk/dat-benchmark/node_modules/hypercore/index.js:1121:34)
    at /Users/cody/junk/dat-benchmark/node_modules/hypercore/index.js:1111:38
    at Request.done [as _callback] (/Users/cody/junk/dat-benchmark/node_modules/hypercore/lib/storage.js:203:5)
    at Request.callback (/Users/cody/junk/dat-benchmark/node_modules/random-access-storage/index.js:161:8)
    at nextTickCallback (/Users/cody/junk/dat-benchmark/node_modules/random-access-storage/index.js:249:7)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at onerror (/Users/cody/junk/dat-benchmark/node_modules/hyperdrive/index.js:92:19)
    at Object.loop [as callback] (/Users/cody/junk/dat-benchmark/node_modules/hyperdrive/index.js:139:21)
    at Feed._onclose (/Users/cody/junk/dat-benchmark/node_modules/hypercore/index.js:1121:25)
    at /Users/cody/junk/dat-benchmark/node_modules/hypercore/index.js:1111:38
    [... lines matching original stack trace ...]
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

### Debug Logs

```
  dat-node Stream close +0ms
Donezies with  f93346bb5013762841c259891d63df91f4e4071ca449e5ac019a53713d2a2c06
  dat-node leaveNetwork() +964ms
```

**Comment by karissa** [comment]
Is it possible you could be calling `dat.close` twice?

**Comment by joehand** [comment]
Related to #226  perhaps? Though now I get a similar error in testing. May be an hyperdrive issue

**Comment by AcidLeroy** [comment]
@joehand I can try it with the latest merge and see if that helps.

**Comment by joehand** [comment]
Ya, seeing these errors on latest now too (sometimes?). Hard to tell where this is coming from though... I can try to dig a bit.

**Comment by joehand** [comment]
Okay, this should be fixed now! THanks.
