### ISSUE TITLE
rabin error

### ISSUE THREAD

**Issue by aaronshaf** [datproject/dat-node#82]
dat-node 1.2.2 with both node v6.2.2 and node v7.4.0. Install seems successful, but upon running:

```
/root/dat-express/node_modules/bindings/bindings.js:91
  throw err
  ^

Error: Could not locate the bindings file. Tried:
 → /root/dat-express/node_modules/rabin/build/rabin.node
 → /root/dat-express/node_modules/rabin/build/Debug/rabin.node
 → /root/dat-express/node_modules/rabin/build/Release/rabin.node
 → /root/dat-express/node_modules/rabin/out/Debug/rabin.node
 → /root/dat-express/node_modules/rabin/Debug/rabin.node
 → /root/dat-express/node_modules/rabin/out/Release/rabin.node
 → /root/dat-express/node_modules/rabin/Release/rabin.node
 → /root/dat-express/node_modules/rabin/build/default/rabin.node
 → /root/dat-express/node_modules/rabin/compiled/7.4.0/linux/x64/rabin.node
    at bindings (/root/dat-express/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/root/dat-express/node_modules/rabin/index.js:3:32)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/root/dat-express/node_modules/hyperdrive/archive.js:6:53)
```

**Comment by aaronshaf** [comment]
Ended up working with 6.4.

**Comment by maxogden** [comment]
Hmm that is weird about 6.2 vs 6.4. We have been wrestling with bindings lately and putting a lot of work into http://github.com/mafintosh/prebuild to make all these issues go away hopefully forever :D
